all:
	python -m pip install wheel
	python -m pip install pandas
	python -m pip install scikit-learn
	python -m pip install mlxtend
	cat README.txt
	#
	# IF YOU JUST RAN 'MAKE' BEFORE READING THE README *** SHAME ON YOU ***
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current NB SF 5
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids NB SF 5
	#python featureSelector.py regards_012916.csv 29977 Smoke_current NB SF 5
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR NB SF 5
	#python featureSelector.py regards_012916.csv 29977 death_indicator NB SF 5
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR NB SF 5
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current NB SF 10
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids NB SF 10
	#python featureSelector.py regards_012916.csv 29977 Smoke_current NB SF 10
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR NB SF 10
	#python featureSelector.py regards_012916.csv 29977 death_indicator NB SF 10
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR NB SF 10
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current NB SF 15
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids NB SF 15
	#python featureSelector.py regards_012916.csv 29977 Smoke_current NB SF 15
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR NB SF 15
	#python featureSelector.py regards_012916.csv 29977 death_indicator NB SF 15
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR NB SF 15
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current NB SF 20
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids NB SF 20
	#python featureSelector.py regards_012916.csv 29977 Smoke_current NB SF 20
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR NB SF 20
	#python featureSelector.py regards_012916.csv 29977 death_indicator NB SF 20
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR NB SF 20
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current NB SF 70
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids NB SF 70
	#python featureSelector.py regards_012916.csv 29977 Smoke_current NB SF 70
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR NB SF 70
	#python featureSelector.py regards_012916.csv 29977 death_indicator NB SF 70
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR NB SF 70
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current NB SB 5
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids NB SB 5
	#python featureSelector.py regards_012916.csv 29977 Smoke_current NB SB 5
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR NB SB 5
	#python featureSelector.py regards_012916.csv 29977 death_indicator NB SB 5
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR NB SB 5
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current NB SB 10
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids NB SB 10
	#python featureSelector.py regards_012916.csv 29977 Smoke_current NB SB 10
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR NB SB 10
	#python featureSelector.py regards_012916.csv 29977 death_indicator NB SB 10
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR NB SB 10
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current NB SB 15
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids NB SB 15
	#python featureSelector.py regards_012916.csv 29977 Smoke_current NB SB 15
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR NB SB 15
	#python featureSelector.py regards_012916.csv 29977 death_indicator NB SB 15
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR NB SB 15
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current NB SB 20
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids NB SB 20
	#python featureSelector.py regards_012916.csv 29977 Smoke_current NB SB 20
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR NB SB 20
	#python featureSelector.py regards_012916.csv 29977 death_indicator NB SB 20
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR NB SB 20
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current NB SB 70 &
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids NB SB 70 &
	#python featureSelector.py regards_012916.csv 29977 Smoke_current NB SB 70 &
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR NB SB 70 &
	#python featureSelector.py regards_012916.csv 29977 death_indicator NB SB 70 &
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR NB SB 70 &
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current LR SF 5
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids LR SF 5
	#python featureSelector.py regards_012916.csv 29977 Smoke_current LR SF 5
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR LR SF 5
	#python featureSelector.py regards_012916.csv 29977 death_indicator LR SF 5
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR LR SF 5
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current LR SF 10
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids LR SF 10
	#python featureSelector.py regards_012916.csv 29977 Smoke_current LR SF 10
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR LR SF 10
	#python featureSelector.py regards_012916.csv 29977 death_indicator LR SF 10
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR LR SF 10
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current LR SF 15
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids LR SF 15
	#python featureSelector.py regards_012916.csv 29977 Smoke_current LR SF 15
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR LR SF 15
	#python featureSelector.py regards_012916.csv 29977 death_indicator LR SF 15
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR LR SF 15
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current LR SF 20
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids LR SF 20
	#python featureSelector.py regards_012916.csv 29977 Smoke_current LR SF 20
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR LR SF 20
	#python featureSelector.py regards_012916.csv 29977 death_indicator LR SF 20
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR LR SF 20
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current LR SF 70
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids LR SF 70
	#python featureSelector.py regards_012916.csv 29977 Smoke_current LR SF 70
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR LR SF 70
	#python featureSelector.py regards_012916.csv 29977 death_indicator LR SF 70
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR LR SF 70
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current LR SB 5
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids LR SB 5
	#python featureSelector.py regards_012916.csv 29977 Smoke_current LR SB 5
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR LR SB 5
	#python featureSelector.py regards_012916.csv 29977 death_indicator LR SB 5
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR LR SB 5
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current LR SB 10
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids LR SB 10
	#python featureSelector.py regards_012916.csv 29977 Smoke_current LR SB 10
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR LR SB 10
	#python featureSelector.py regards_012916.csv 29977 death_indicator LR SB 10
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR LR SB 10
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current LR SB 15
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids LR SB 15
	#python featureSelector.py regards_012916.csv 29977 Smoke_current LR SB 15
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR LR SB 15
	#python featureSelector.py regards_012916.csv 29977 death_indicator LR SB 15
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR LR SB 15
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current LR SB 20
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids LR SB 20
	#python featureSelector.py regards_012916.csv 29977 Smoke_current LR SB 20
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR LR SB 20
	#python featureSelector.py regards_012916.csv 29977 death_indicator LR SB 20
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR LR SB 20
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current LR SB 70 &
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids LR SB 70 &
	#python featureSelector.py regards_012916.csv 29977 Smoke_current LR SB 70 &
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR LR SB 70 &
	#python featureSelector.py regards_012916.csv 29977 death_indicator LR SB 70 &
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR LR SB 70 &
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current RF SF 5
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids RF SF 5
	#python featureSelector.py regards_012916.csv 29977 Smoke_current RF SF 5
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR RF SF 5
	#python featureSelector.py regards_012916.csv 29977 death_indicator RF SF 5
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR RF SF 5
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current RF SF 10
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids RF SF 10
	#python featureSelector.py regards_012916.csv 29977 Smoke_current RF SF 10
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR RF SF 10
	#python featureSelector.py regards_012916.csv 29977 death_indicator RF SF 10
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR RF SF 10
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current RF SF 15
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids RF SF 15
	#python featureSelector.py regards_012916.csv 29977 Smoke_current RF SF 15
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR RF SF 15
	#python featureSelector.py regards_012916.csv 29977 death_indicator RF SF 15
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR RF SF 15
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current RF SF 20
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids RF SF 20
	#python featureSelector.py regards_012916.csv 29977 Smoke_current RF SF 20
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR RF SF 20
	#python featureSelector.py regards_012916.csv 29977 death_indicator RF SF 20
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR RF SF 20
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current RF SF 70
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids RF SF 70
	#python featureSelector.py regards_012916.csv 29977 Smoke_current RF SF 70
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR RF SF 70
	#python featureSelector.py regards_012916.csv 29977 death_indicator RF SF 70
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR RF SF 70
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current RF SB 5
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids RF SB 5
	#python featureSelector.py regards_012916.csv 29977 Smoke_current RF SB 5
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR RF SB 5
	#python featureSelector.py regards_012916.csv 29977 death_indicator RF SB 5
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR RF SB 5
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current RF SB 10
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids RF SB 10
	#python featureSelector.py regards_012916.csv 29977 Smoke_current RF SB 10
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR RF SB 10
	#python featureSelector.py regards_012916.csv 29977 death_indicator RF SB 10
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR RF SB 10
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current RF SB 15
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids RF SB 15
	#python featureSelector.py regards_012916.csv 29977 Smoke_current RF SB 15
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR RF SB 15
	#python featureSelector.py regards_012916.csv 29977 death_indicator RF SB 15
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR RF SB 15
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current RF SB 20
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids RF SB 20
	#python featureSelector.py regards_012916.csv 29977 Smoke_current RF SB 20
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR RF SB 20
	#python featureSelector.py regards_012916.csv 29977 death_indicator RF SB 20
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR RF SB 20
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current RF SB 70 &
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids RF SB 70 &
	#python featureSelector.py regards_012916.csv 29977 Smoke_current RF SB 70 &
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR RF SB 70 &
	#python featureSelector.py regards_012916.csv 29977 death_indicator RF SB 70 &
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR RF SB 70 &
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current KNN SF 5 &
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids KNN SF 5 &
	#python featureSelector.py regards_012916.csv 29977 Smoke_current KNN SF 5 &
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR KNN SF 5 &
	#python featureSelector.py regards_012916.csv 29977 death_indicator KNN SF 5 &
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR KNN SF 5 &
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current KNN SF 10 &
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids KNN SF 10 &
	#python featureSelector.py regards_012916.csv 29977 Smoke_current KNN SF 10 &
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR KNN SF 10 &
	#python featureSelector.py regards_012916.csv 29977 death_indicator KNN SF 10 &
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR KNN SF 10 &
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current KNN SF 15 &
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids KNN SF 15 &
	#python featureSelector.py regards_012916.csv 29977 Smoke_current KNN SF 15 &
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR KNN SF 15 &
	#python featureSelector.py regards_012916.csv 29977 death_indicator KNN SF 15 &
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR KNN SF 15 &
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current KNN SF 20 &
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids KNN SF 20 &
	#python featureSelector.py regards_012916.csv 29977 Smoke_current KNN SF 20 &
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR KNN SF 20 &
	#python featureSelector.py regards_012916.csv 29977 death_indicator KNN SF 20 &
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR KNN SF 20 &
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current KNN SB 5 &
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids KNN SB 5 &
	#python featureSelector.py regards_012916.csv 29977 Smoke_current KNN SB 5 &
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR KNN SB 5 &
	#python featureSelector.py regards_012916.csv 29977 death_indicator KNN SB 5 &
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR KNN SB 5 &
	# Things take a really long time to run beyond this point!!!
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current KNN SB 10 &
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids KNN SB 10 &
	#python featureSelector.py regards_012916.csv 29977 Smoke_current KNN SB 10 &
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR KNN SB 10 &
	#python featureSelector.py regards_012916.csv 29977 death_indicator KNN SB 10 &
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR KNN SB 10 &
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current KNN SB 15 &
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids KNN SB 15 &
	#python featureSelector.py regards_012916.csv 29977 Smoke_current KNN SB 15 &
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR KNN SB 15 &
	#python featureSelector.py regards_012916.csv 29977 death_indicator KNN SB 15 &
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR KNN SB 15 &
	#
	#python featureSelector.py regards_012916.csv 29977 Alcohol_use_current KNN SB 20 &
	#python featureSelector.py regards_012916.csv 29977 Reg_Nsaids KNN SB 20 &
	#python featureSelector.py regards_012916.csv 29977 Smoke_current KNN SB 20 &
	#python featureSelector.py regards_012916.csv 29977 Diabetes_SR KNN SB 20 &
	#python featureSelector.py regards_012916.csv 29977 death_indicator KNN SB 20 &
	#python featureSelector.py regards_012916.csv 29977 Stroke_SR KNN SB 20 &
	#
	# Processes beyond this point are using a modified version of the DB (read the paper for an explanation)
	#
	#python featureSelector.py regards_012916_woALC.csv 29977 Alcohol_use_current NB SF 67 &
	#python featureSelector.py regards_012916_woALC.csv 29977 Alcohol_use_current LR SF 67 &
	#python featureSelector.py regards_012916_woALC.csv 29977 Alcohol_use_current RF SF 67 &
	#python featureSelector.py regards_012916_woSMKmod.csv 29977 Smoke_current NB SF 66 &
	#python featureSelector.py regards_012916_woSMKmod.csv 29977 Smoke_current LR SF 66 &
	#python featureSelector.py regards_012916_woSMKmod.csv 29977 Smoke_current RF SF 66 &
	#python featureSelector.py regards_012916_woSMK.csv 29977 Smoke_current NB SF 67 &
	#python featureSelector.py regards_012916_woSMK.csv 29977 Smoke_current LR SF 67 &
	#python featureSelector.py regards_012916_woSMK.csv 29977 Smoke_current RF SF 67 &
	#
	#python featureSelector.py regards_012916_woALC.csv 29977 Alcohol_use_current NB SB 67 &
	#python featureSelector.py regards_012916_woALC.csv 29977 Alcohol_use_current LR SB 67 &
	#python featureSelector.py regards_012916_woALC.csv 29977 Alcohol_use_current RF SB 67 &
	python featureSelector.py regards_012916_woSMKmod.csv 29977 Smoke_current NB SB 66 &
	python featureSelector.py regards_012916_woSMKmod.csv 29977 Smoke_current LR SB 66 &
	python featureSelector.py regards_012916_woSMKmod.csv 29977 Smoke_current RF SB 66 &
	#python featureSelector.py regards_012916_woSMK.csv 29977 Smoke_current NB SB 67 &
	#python featureSelector.py regards_012916_woSMK.csv 29977 Smoke_current LR SB 67 &
	#python featureSelector.py regards_012916_woSMK.csv 29977 Smoke_current RF SB 67 &
